# Rearranging Elements (Flipping & Rotating)
## 1. flip()
- Reverses array elements along the specified axis.
- Can work on multiple dimensions (e.g., flipping rows or columns).

## 2. fliplr()
- Flip array in the left/right (horizontal) direction.
- Think of this as a mirror on the vertical axis.

## 3. flipud()
- Flip array in the up/down (vertical) direction.
- Think of this as a mirror on the horizontal axis.

## 4. rot90(k=1)
- Rotates an array by 90 degrees in the counter-clockwise direction.
- You can rotate multiple times: k=1 for 90°, k=2 for 180°, etc.



In [5]:
import numpy as np 

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

flipped_rows = np.flip(arr, axis=0)  # Flips up/down
flipped_cols = np.flip(arr, axis=1)  # Flips left/right

In [6]:
flipped_rows

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [7]:
flipped_cols

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [8]:
flipped_lr = np.fliplr(arr)

In [9]:
print(flipped_lr)

[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [11]:
np.flipud(arr)

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [12]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.rot90(arr, k=1)

array([[3, 6, 9],
       [2, 5, 8],
       [1, 4, 7]])

In [14]:
np.rot90(arr, k=2)

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

--- 

In [15]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9],
                [10,11,12]])

In [17]:
np.flip(arr,axis = 0 )

array([[10, 11, 12],
       [ 7,  8,  9],
       [ 4,  5,  6],
       [ 1,  2,  3]])

In [18]:
np.flip(arr,axis = 1 )

array([[ 3,  2,  1],
       [ 6,  5,  4],
       [ 9,  8,  7],
       [12, 11, 10]])

In [19]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

In [22]:
np.flip(arr)

array([[16, 15, 14, 13],
       [12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [23]:
np.flip(arr, axis = 0)

array([[13, 14, 15, 16],
       [ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [24]:
np.flip(arr, axis = 1)

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9],
       [16, 15, 14, 13]])

In [25]:
np.fliplr(arr)

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9],
       [16, 15, 14, 13]])

In [27]:
np.flipud(arr)

array([[13, 14, 15, 16],
       [ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])