# Reshape array Returns Copy or View?

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [2]:
arr.size

8

In [3]:
print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


- The example above returns the original array, so it is a view.



---
## Unknown Dimension
- You are allowed to have one "unknown" dimension.

- Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

- Pass -1 as the value, and NumPy will calculate this number for you.

- Note: We can not pass -1 to more than one dimension.

In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [5]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])


In [7]:
arr.reshape(2,-1)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

--- 
## Flattening the arrays
- Flattening array means converting a multidimensional array into a 1D array.

- We can use reshape(-1) to do this.

In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6]])


In [9]:
arr.reshape(-1) # flattening the array

array([1, 2, 3, 4, 5, 6])

In [10]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
# using flatten 
arr.flatten()

array([1, 2, 3, 4, 5, 6])

In [16]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.reshape(-1)[0] = 69
print(arr)

[[69  2  3]
 [ 4  5  6]]


In [23]:
arr.flatten()[0]

69

In [27]:
flat_arr = arr.flatten()
print(flat_arr)

[69  2  3  4  5  6]


In [28]:
flat_arr[0] = 777

In [29]:
flat_arr

array([777,   2,   3,   4,   5,   6])

In [30]:
arr

array([[69,  2,  3],
       [ 4,  5,  6]])

In [31]:
# flatten array creates a copy while reshape creates a view 

---
## Ravel ?
- returns a view just like reshape
- while "Flatten" returns a copy

In [32]:
arr

array([[69,  2,  3],
       [ 4,  5,  6]])

In [33]:
arr.ravel()

array([69,  2,  3,  4,  5,  6])

In [34]:
raveled_arr = arr.ravel()
raveled_arr[0] = 11111111

In [35]:
raveled_arr.base

array([[11111111,        2,        3],
       [       4,        5,        6]])