# Broadcasting in NumPy
## We can code faster with vectorization and broadcasting in NumPy. These techniques are key to boosting performance in numerical operations by avoiding slow loops and memory inefficiency.
## While Python loops are convenient, they don’t take advantage of the optimized memory and computation that libraries like NumPy provide.

In [2]:
''' Broadcasting with Scalar : 
Broadcasting is often used when you want to perform an operation on an array
and a scalar value (e.g., add a number to all elements of an array). ''' 
import numpy as np 
arr = np.array([1, 2, 3, 4, 5])
result = arr + 10 # Broadcasting: 10 is added to all elements
print(result) # Output: [11 12 13 14 15]

[11 12 13 14 15]


In [5]:
# Broadcasting a 2D Array and a 1D Array
arr1 = np.array([10,20,30,40,50])
arr2 = np.array([[5,5,5,5,5],[5,5,5,5,5]])


In [6]:
arr1+arr2

array([[15, 25, 35, 45, 55],
       [15, 25, 35, 45, 55]])

In [7]:
data = np.array([[10, 20, 30],
[15, 25, 35],
[20, 30, 40],
[25, 35, 45],
[30, 40, 50]])
# Calculating mean and standard deviation for each feature (column)
mean = data.mean(axis=0)
std = data.std(axis=0)
# Normalizing the data using broadcasting
normalized_data = (data - mean) / std
print(normalized_data)

[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]
