In [1]:
import numpy as np 

In [2]:
arr = np.array([1,3,54,74,243]) #1D array 
print(arr)

[  1   3  54  74 243]


In [3]:
arr2 = np.array([[12,32,65],[24,75,83]]) #2D array
print(arr2)

[[12 32 65]
 [24 75 83]]


In [4]:
arr3 = np.array([[12,32,65],[24,75,83],[27,83,92]]) #3D array
print(arr3)

[[12 32 65]
 [24 75 83]
 [27 83 92]]


# TYPES OF ARRAY 

In [5]:
#identity array / matrix
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
#zero array
print(np.zeros(5))
print('_'*100)
print(np.zeros((3,4)))

[0. 0. 0. 0. 0.]
____________________________________________________________________________________________________
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
# array full with a specific value 
np.full((3,5),69)

array([[69, 69, 69, 69, 69],
       [69, 69, 69, 69, 69],
       [69, 69, 69, 69, 69]])

In [8]:
# more like "addition range"
np.arange(1, 100, 10) # [1, 3, 5, 7, 9] (like range)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [9]:
np.linspace(0, 20,6) # (evenly spaced)

array([ 0.,  4.,  8., 12., 16., 20.])

# ARRAY PROPERTIES


In [ ]:
arr = np.array([[10, 20, 30], [40, 50, 60]])

In [12]:
arr.size # does not contain parenthesis 

9

In [16]:
arr.dtype # provides data type

dtype('float64')

In [17]:
arr.shape # gives the shape of array 

(3, 3)

In [18]:
arr.ndim # provides the dimensions

2

## Changing Data Types

In [19]:
arr = np.array([[10, 20, 30], [40, 50, 60]])

In [20]:
arr.dtype

dtype('int64')

In [21]:
arr.astype(np.int32)

array([[10, 20, 30],
       [40, 50, 60]], dtype=int32)

In [24]:
arr = np.array([1, 2, 3], dtype=np.float32) 
print(arr)
print(arr.dtype)

[1. 2. 3.]
float32


## Reshaping and Flattening Arrays

In [26]:
arr = np.array([[20,325,32,53],[64,38,254,539]])

In [28]:
arr.shape

(2, 4)

In [30]:
arr.reshape((8,1))

array([[ 20],
       [325],
       [ 32],
       [ 53],
       [ 64],
       [ 38],
       [254],
       [539]])

In [33]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print()
arr.reshape((3,2))

[[1 2 3]
 [4 5 6]]



array([[1, 2],
       [3, 4],
       [5, 6]])

In [35]:
flattened = arr.flatten() # Convert 2D → 1D 
print(flattened)

[1 2 3 4 5 6]


In [36]:
arr3 = np.array([[12,32,65],[24,75,83],[27,83,92]]) #3D array
print(flattene)

[1 2 3 4 5 6]
