# NumPy supports various data types (also called dtypes), and understanding them is crucial for optimizing memory usage and performance.
---
## Common Data Types in NumPy:
- int32 , int64 : Integer types with different bit sizes.
- float32 , float64 : Floating-point types with different precision.
- bool : Boolean data type.
- complex64, complex128 : Complex number types.
- object : For storing objects (e.g., Python objects, strings).
---

In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype) # Output: int64 or int32 depending on the system)

int64


## Changind Data Types

In [2]:
arr.astype(np.float32)

array([1., 2., 3., 4., 5.], dtype=float32)

In [3]:
#also 
arr.astype("int32")

array([1, 2, 3, 4, 5], dtype=int32)

In [4]:
#while creating also we can define the datatype 
complex_arr = np.array([1+2j, 4+6j , 23+7j])

In [5]:
complex_arr.dtype

dtype('complex128')

In [10]:
#while creating also we can define the datatype 
bool_arr = np.array([True,False,False,True], dtype= "bool")

In [12]:
obj_arr = np.array([["Krish", True , 64 , "HELLO" , {"Name": "Colour "}]])

In [15]:
obj_arr.dtype

dtype('O')

In [16]:
obj_arr.astype("object")

array([['Krish', True, 64, 'HELLO', {'Name': 'Colour '}]], dtype=object)

In [17]:
obj_arr.dtype

dtype('O')

In [18]:
bool_arr.dtype

dtype('bool')

In [19]:
# Can we type-cast bool to int ??
# or object to int / float ?  ..... let's seee
bool_arr.astype("int32")

array([1, 0, 0, 1], dtype=int32)

In [21]:
bool_arr = np.array([True,False,False,True], dtype= "bool")

In [22]:
bool_arr.astype("float")

array([1., 0., 0., 1.])

In [24]:
bool_arr = np.array([True,False,False,True], dtype= "bool")
bool_arr.astype("object")

array([True, False, False, True], dtype=object)

In [25]:
obj_arr

array([['Krish', True, 64, 'HELLO', {'Name': 'Colour '}]], dtype=object)

In [26]:
obj_arr.astype("bool")

array([[ True,  True,  True,  True,  True]])

In [27]:
obj_arr

array([['Krish', True, 64, 'HELLO', {'Name': 'Colour '}]], dtype=object)

In [28]:
obj_arr.astype("int")

ValueError: invalid literal for int() with base 10: 'Krish'

In [30]:
obj_arr.astype("float")

ValueError: could not convert string to float: 'Krish'

In [31]:
# Downcasting to Save Memory
arr_int64 = np.array([1, 2, 3], dtype=np.int64)
arr_int32 = np.array([1, 2, 3], dtype=np.int32)
print(arr_int64.nbytes) # Output: 24 bytes (3 elements * 8 bytes each)
print(arr_int32.nbytes) # Output: 12 bytes (3 elements * 4 bytes each)

24
12


In [32]:
# String Data Type in NumPy
arr = np.array(['apple', 'banana', 'cherry'], dtype='U10') # Unicode string array
print(arr)

['apple' 'banana' 'cherry']


In [33]:
arr

array(['apple', 'banana', 'cherry'], dtype='<U10')

In [34]:
arr.astype("str")

array(['apple', 'banana', 'cherry'], dtype='<U10')

In [35]:
arr.astype("int")

ValueError: invalid literal for int() with base 10: 'apple'

In [36]:
arr.astype("bool")

ValueError: invalid literal for int() with base 10: 'apple'

In [37]:
arr.astype("complex")

ValueError: complex() arg is a malformed string

In [38]:
arr.astype("object")

array(['apple', 'banana', 'cherry'], dtype=object)

## Conclusion: 
- we can convert int to and float to any data type .
- we can convert bool to any data type .
- we can convert object to only bool data type not to int of float !!
- we can'not convert any str data type into numeric , so we can't convert str -> int / float / bool but converting it to object is possible 