# Indexing is same as python lists

In [1]:

import numpy as np
arr = np.array([[10,35,24],[34,75,21]])

In [2]:
flat = arr.flatten()

In [3]:
print(flat)

[10 35 24 34 75 21]


In [4]:
print(arr[0])

[10 35 24]


In [5]:
arr[1] #provides the array element 

array([34, 75, 21])

In [6]:
#using flattened array
flat[2:7]

array([24, 34, 75, 21])

In [7]:
flat[:] # complete

array([10, 35, 24, 34, 75, 21])

In [8]:
#reversed arrar
flat[::-1]

array([21, 75, 34, 24, 35, 10])

## Slicing returns a view, not a copy! Changes affect the original array

In [12]:
arr1 = np.array([[93,21,83,123],[35,62,912,23]])

In [14]:
print(arr1.flatten())

[ 93  21  83 123  35  62 912  23]


In [16]:
k = arr1[::-1] #containing reversed array
print(k)

[ 23 912  62  35 123  83  21  93]


In [20]:
k[2] = 69
print(k)

[ 23 912  69  35 123  83  21  93]


In [21]:
#taking a slice
sliced = arr1[2:6]
print(sliced)
sliced[2] = 111111
print(sliced)

[ 83 123  35  69]
[    83    123 111111     69]


In [22]:
#checking the oriinal array , as if it changed 
arr1

array([    93,     21,     83,    123, 111111,     69,    912,     23])

## To create a copy and it should not change the original array we use ".copy()"

In [23]:
arr1 #original array rn

array([    93,     21,     83,    123, 111111,     69,    912,     23])

In [25]:
#making a copy of array 
newarr1 = arr1[2:6].copy()
print(newarr1)

[    83    123 111111     69]


In [26]:
# changing the values and check for if orginial has changed or nto
newarr1[2] = 2222
print(newarr1)
print()
print(arr1) 

[  83  123 2222   69]

[    93     21     83    123 111111     69    912     23]


## Fancy Indexing & Boolean Masking

In [32]:
# Fancy Indexing (Select Multiple Elements)

arrayy = np.array([13,69,73,96,932,9269])
index = [1,3,5] #indices to select 
print(arrayy[index]) # syntax : arr[idx]

[  69   96 9269]


In [39]:
# Boolean Masking (Filter Data)

arr = np.array([10, 20, 30, 40, 50])
mask = (arr < 30) # provide a condition without any square brackets
print(arr[mask])

[10 20]
