# Understanding Axes in NumPy
## Each dimension in a NumPy array is called an axis. Axes are numbered starting from 0.
- 1D array → 1 axis (axis 0)
- 2D array → 2 axes (axis 0 = rows, axis 1 = columns)
- 3D array → 3 axes (axis 0 = depth, axis 1 = rows, axis 2 = columns)

In [1]:
import numpy as np 

In [2]:
array1D = np.array([20,384,34,62,84])
array2D = np.array([
    [63,29,543,24],
    [52,67,34,24]
])

array3D = np.array([
    [[63,29,543,24],
    [52,67,34,24]],
    
    [[63,29,543,24],
    [52,67,34,24]]
]) # an array with 2D elements as depth 

In [4]:
array1D.ndim

1

In [5]:
array2D.ndim

2

In [6]:
array3D.ndim

3

In [7]:
psudo3D = np.array([[4,72,92],
                    [35,84,92],
                    [62,63,53]
                   ])

In [8]:
psudo3D.ndim

2

# Indexing in Multidimensional Arrays

In [10]:
array1D

array([ 20, 384,  34,  62,  84])

In [11]:
array1D[1]

384

In [14]:
array1D[4]

84

In [15]:
array2D

array([[ 63,  29, 543,  24],
       [ 52,  67,  34,  24]])

In [16]:
array2D[0][3]

24

In [17]:
array2D[1][2] # should print 34

34

In [18]:
#using row and column indices.

array2D[1,3] # -> 24

24

In [19]:
#slicing in 2D

array2D[:] # -> should return the whole array

array([[ 63,  29, 543,  24],
       [ 52,  67,  34,  24]])

In [22]:
array2D[:,2] # -> 543 , 34

array([543,  34])

In [24]:
# access element - 67 
array2D[1,1]  #1 indexing


67

In [25]:
array2D[1][1] #2 indexing 


67

In [29]:
array2D[1:,1:2] #slicing

array([[67]])

# Indexing in 3D Arrays

In [30]:
array3D

array([[[ 63,  29, 543,  24],
        [ 52,  67,  34,  24]],

       [[ 63,  29, 543,  24],
        [ 52,  67,  34,  24]]])

In [31]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
[[7, 8, 9], [10, 11, 12]]])

In [32]:
arr3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [33]:
# Output of arr3D.shape is → (depth, rows, columns)
print(arr3D.shape) 

(2, 2, 3)


In [34]:
#Accessing elements in 3D:
# to access 9 
arr3D[1,0,2]

9

In [35]:
# get 1st row from both sheets
arr3D[0:2,0,:]

array([[1, 2, 3],
       [7, 8, 9]])

# Selecting Data Along Axes

In [36]:
# Get all rows of the first column
array3D

array([[[ 63,  29, 543,  24],
        [ 52,  67,  34,  24]],

       [[ 63,  29, 543,  24],
        [ 52,  67,  34,  24]]])

In [37]:
array3D[:,:,0]

array([[63, 52],
       [63, 52]])

In [39]:
# Get the first row from each "sheet" in a 3D array
new_arr3D = array3D[:,0,:]
print(new_arr3D)

[[ 63  29 543  24]
 [ 63  29 543  24]]


# Changing Data Along an Axis

In [43]:
# Replace all elements in column 1 with 0
array3D[:,:,0] = 0 
print(array3D)

[[[  0  29 543  24]
  [  0  67  34  24]]

 [[  0  29 543  24]
  [  0  67  34  24]]]


In [44]:
# add 69 in all elements in column 2 
array3D[:,:,1] = 69

In [45]:
array3D

array([[[  0,  69, 543,  24],
        [  0,  69,  34,  24]],

       [[  0,  69, 543,  24],
        [  0,  69,  34,  24]]])