# Exercises for Practice
- Create a 3×3 array filled with random numbers and print its shape.
- Convert an array of floats [1.1, 2.2, 3.3] into integers.
- Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].
- Reshape a 1D array of size 9 into a 3×3 matrix.

In [2]:
import numpy as np
arr = np.array([[29,23,73],[35,75,18],[25,75,82]])
arr.shape

(3, 3)

In [4]:
f_array = np.array([[1.1, 2.2, 3.3]])
f_array.astype(np.int32)

array([[1, 2, 3]], dtype=int32)

In [6]:
#other way of doing so 
arr = np.array([1.1, 2.2, 3.3], dtype="int32")
print(arr)

[1 2 3]


In [7]:
arr1 = np.array([1, 2, 3, 4, 5, 6])
mask = (arr1%2==0)
print(arr1[mask])

[2 4 6]


In [8]:
arr1 

array([1, 2, 3, 4, 5, 6])

In [10]:
arr1d = np.array([64,48,893,26,94,72,82,63,912])
print(f"Before changing : arr1d.size)
print("after changing")
arr1d = arr1d.reshape((3,3))
print(arr1d.size)
arr1d

9
after changing
9


array([[ 64,  48, 893],
       [ 26,  94,  72],
       [ 82,  63, 912]])